spring:
  profiles:
    group:
      dev:
        - dev
        - jwt
      prod:
        - prod
        - jwt
        - secret

logging:
  level:
    com.ll.mb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE # org.hibernate.orm.jdbc.bind와 org.hibernate.orm.jdbc.extract 대신 사용
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # org.hibernate.orm.jdbc.bind 대신 사용
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE # org.hibernate.orm.jdbc.extract 대신 사용
    org.springframework.transaction.interceptor: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs



